export const advice = [
    "About 99% of the time, the right time is right now.",
    "No one is as impressed with your possessions as you are.",
    "Don't ever work for someone you don't want to become.",
    "Cultivate 12 people who love you, because they are worth more than 12 million people who like you.",
    "Don't keep making the same mistakes; try to make new mistakes.",
    "If you stop to listen to a musician or street performer for more than a minute, you owe them a dollar.",
    "Anything you say before the word “but” does not count.",
    "When you forgive others, they may not notice, but you will heal. Forgiveness is not something we do for others; it is a gift to ourselves.",
    "Courtesy costs nothing. Lower the toilet seat after use. Let the people in the elevator exit before you enter. Return shopping carts to their designated areas. When you borrow something, return it better shape (filled up, cleaned) than when you got it.",
    "Whenever there is an argument between two sides, find the third side.",
    "Efficiency is highly overrated; Goofing off is highly underrated. Regularly scheduled sabbaths, sabbaticals, vacations, breaks, aimless walks and time off are essential for top performance of any kind. The best work ethic requires a good rest ethic.",
    "When you lead, your real job is to create more leaders, not more followers.",
    "Criticize in private, praise in public.",
    "Life lessons will be presented to you in the order they are needed. Everything you need to master the lesson is within you. Once you have truly learned a lesson, you will be presented with the next one. If you are alive, that means you still have lessons to learn.",
    "It is the duty of a student to get everything out of a teacher, and the duty of a teacher to get everything out of a student.",
    "If winning becomes too important in a game, change the rules to make it more fun. Changing rules can become the new game.",
    "Ask funders for money, and they’ll give you advice; but ask for advice and they’ll give you money.",
    "Productivity is often a distraction. Don’t aim for better ways to get through your tasks as quickly as possible, rather aim for better tasks that you never want to stop doing.",
    "Immediately pay what you owe to vendors, workers, contractors. They will go out of their way to work with you first next time.",
    "The biggest lie we tell ourselves is “I don't need to write this down because I will remember it.”",
    "Your growth as a conscious being is measured by the number of uncomfortable conversations you are willing to have.",
    "Speak confidently as if you are right, but listen carefully as if you are wrong.",
    "Handy measure the distance between your fingertips of your outstretched arms at shoulder level is your height.",
    "The consistency of your endeavors (exercise, companionship, work) is more important than the quantity. Nothing beats small things done every day, which is way more important than what you do occasionally.",
    "Making art is not selfish; it’s for the rest of us. If you don’t do your thing, you are cheating us.",
    "Never ask a woman if she is pregnant. Let her tell you if she is.",
    "Three things you need The ability to not give up something till it works, the ability to give up something that does not work, and the trust in other people to help you distinguish between the two.",
    "When public speaking, pause frequently. Pause before you say something in a new way, pause after you have said something you believe is important, and pause as a relief to let listeners absorb details.",
    "There is no such thing as being “on time.” You are either late or you are early. Your choice.",
    "Ask anyone you admire Their lucky breaks happened on a detour from their main goal. So embrace detours. Life is not a straight line for anyone.",
    "The best way to get a correct answer on the internet is to post an obviously wrong answer and wait for someone to correct you.",
    "You’ll get 10x better results by elevating good behavior rather than punishing bad behavior, especially in children and animals.",
    "Spend as much time crafting the subject line of an email as the message itself because the subject line is often the only thing people read.",
    "Don’t wait for the storm to pass; dance in the rain.",
    "When checking references for a job applicant, employers may be reluctant or prohibited from saying anything negative, so leave or send a message that says, “Get back to me if you highly recommend this applicant as super great.” If they don’t reply take that as a negative.",
    "Use a password manager Safer, easier, better.",
    "Half the skill of being educated is learning what you can ignore.",
    "The advantage of a ridiculously ambitious goal is that it sets the bar very high so even in failure it may be a success measured by the ordinary.",
    "A great way to understand yourself is to seriously reflect on everything you find irritating in others.",
    "Keep all your things visible in a hotel room, not in drawers, and all gathered into one spot. That way you’ll never leave anything behind. If you need to have something like a charger off to the side, place a couple of other large items next to it, because you are less likely to leave 3 items behind than just one.",
    "Denying or deflecting a compliment is rude. Accept it with thanks, even if you believe it is not deserved.",
    "Always read the plaque next to the monument.",
    "When you have some success, the feeling of being an imposter can be real. Who am I fooling? But when you create things that only you — with your unique talents and experience — can do, then you are absolutely not an imposter. You are the ordained. It is your duty to work on things that only you can do.",
    "What you do on your bad days matters more than what you do on your good days.",
    "Make stuff that is good for people to have.",
    "When you open paint, even a tiny bit, it will always find its way to your clothes no matter how careful you are. Dress accordingly.",
    "To keep young kids behaving on a car road trip, have a bag of their favorite candy and throw a piece out the window each time they misbehave.",
    "You cannot get smart people to work extremely hard just for money.",
    "When you don’t know how much to pay someone for a particular task, ask them “what would be fair” and their answer usually is.",
    "90% of everything is crap. If you think you don’t like opera, romance novels, TikTok, country music, vegan food, NFTs, keep trying to see if you can find the 10% that is not crap.",
    "You will be judged on how well you treat those who can do nothing for you.",
    "We tend to overestimate what we can do in a day, and underestimate what we can achieve in a decade. Miraculous things can be accomplished if you give it ten years. A long game will compound small gains to overcome even big mistakes.",
    "Thank a teacher who changed your life.",
    "You can't reason someone out of a notion that they didn’t reason themselves into.",
    "Your best job will be one that you were unqualified for because it stretches you. In fact only apply to jobs you are unqualified for.",
    "Buy used books. They have the same words as the new ones. Also libraries.",
    "You can be whatever you want, so be the person who ends meetings early.",
    "A wise man said, “Before you speak, let your words pass through three gates. At the first gate, ask yourself, “Is it true?” At the second gate ask, “Is it necessary?” At the third gate ask, “Is it kind?”",
    "Take the stairs.",
    "What you actually pay for something is at least twice the listed price because of the energy, time, money needed to set it up, learn, maintain, repair, and dispose of at the end. Not all prices appear on labels. Actual costs are 2x listed prices.",
    "When you arrive at your room in a hotel, locate the emergency exits. It only takes a minute.",
    "The only productive way to answer “what should I do now?” is to first tackle the question of “who should I become?”",
    "Average returns sustained over an above-average period of time yield extraordinary results. Buy and hold.",
    "It’s thrilling to be extremely polite to rude strangers.",
    "It’s possible that a not-so smart person, who can communicate well, can do much better than a super smart person who can’t communicate well. That is good news because it is much easier to improve your communication skills than your intelligence.",
    "Getting cheated occasionally is the small price for trusting the best of everyone, because when you trust the best in others, they generally treat you best.",
    "Art is whatever you can get away with.",
    "For the best results with your children, spend only half the money you think you should, but double the time with them.",
    "Purchase the most recent tourist guidebook to your home town or region. You’ll learn a lot by playing the tourist once a year.",
    "Don't wait in line to eat something famous. It is rarely worth the wait.",
    "To rapidly reveal the true character of a person you just met, move them onto an abysmally slow internet connection. Observe.",
    "Prescription for popular success do something strange. Make a habit of your weird.",
    "Be a pro. Back up your back up. Have at least one physical backup and one backup in the cloud. Have more than one of each. How much would you pay to retrieve all your data, photos, notes, if you lost them? Backups are cheap compared to regrets.",
    "Don't believe everything you think you believe.",
    "To signal an emergency, use the rule of three; 3 shouts, 3 horn blasts, or 3 whistles.",
    "At a restaurant do you order what you know is great, or do you try something new? Do you make what you know will sell or try something new? Do you keep dating new folks or try to commit to someone you already met? The optimal balance for exploring new things vs exploiting them once found is 1/3. Spend 1/3 of your time on exploring and 2/3 time on deepening. It is harder to devote time to exploring as you age because it seems unproductive, but aim for 1/3.",
    "Actual great opportunities do not have “Great Opportunities” in the subject line.",
    "When introduced to someone make eye contact and count to 4. You’ll both remember each other.",
    "Take note if you find yourself wondering “Where is my good knife? Or, where is my good pen?” That means you have bad ones. Get rid of those.",
    "When you are stuck, explain your problem to others. Often simply laying out a problem will present a solution. Make “explaining the problem” part of your troubleshooting process.",
    "When buying a garden hose, an extension cord, or a ladder, get one substantially longer than you think you need. It’ll be the right size.",
    "Don't bother fighting the old; just build the new.",
    "Your group can achieve great things way beyond your means simply by showing people that they are appreciated.",
    "When someone tells you about the peak year of human history, the period of time when things were good before things went downhill, it will always be the years of when they were 10 years old — which is the peak of any human’s existence.",
    "You are as big as the things that make you angry.",
    "When speaking to an audience it’s better to fix your gaze on a few people than to “spray” your gaze across the room. Your eyes telegraph to others whether you really believe what you are saying.",
    "Habit is far more dependable than inspiration. Make progress by making habits. Don't focus on getting into shape. Focus on becoming the kind of person who never misses a workout.",
    "When negotiating, don't aim for a bigger piece of the pie; aim to create a bigger pie.",
    "If you repeated what you did today 365 more times will you be where you want to be next year?",
    "You see only 2% of another person, and they see only 2% of you. Attune yourselves to the hidden 98%.",
    "Your time and space are limited. Remove, give away, throw out things in your life that don't spark joy any longer in order to make room for those that do.",
    "Our descendants will achieve things that will amaze us, yet a portion of what they will create could have been made with today’s materials and tools if we had had the imagination. Think bigger.",
    "For a great payoff be especially curious about the things you are not interested in.",
    "Focus on directions rather than destinations. Who knows their destiny? But maintain the right direction and you’ll arrive at where you want to go.",
    "Every breakthrough is at first laughable and ridiculous. In fact if it did not start out laughable and ridiculous, it is not a breakthrough.",
    "If you loan someone $20 and you never see them again because they are avoiding paying you back, that makes it worth $20.",
    "Copying others is a good way to start. Copying yourself is a disappointing way to end.",
    "The best time to negotiate your salary for a new job is the moment AFTER they say they want you, and not before. Then it becomes a game of chicken for each side to name an amount first, but it is to your advantage to get them to give a number before you do.",
    "Rather than steering your life to avoid surprises, aim directly for them.",
    "Don't purchase extra insurance if you are renting a car with a credit card.",
    "If your opinions on one subject can be predicted from your opinions on another, you may be in the grip of an ideology. When you truly think for yourself your conclusions will not be predictable.",
    "Aim to die broke. Give to your beneficiaries before you die; it’s more fun and useful. Spend it all. Your last check should go to the funeral home and it should bounce.",
    "The chief prevention against getting old is to remain astonished.", 
    "That thing that made you weird as a kid could make you great as an adult — if you don’t lose it.",
    "If you have any doubt at all about being able to carry a load in one trip, do yourself a huge favor and make two trips.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. At your funeral people will not recall what you did; they will only remember how you made them feel.",
    "Recipe for success: under-promise and over-deliver.",
    "It’s not an apology if it comes with an excuse. It is not a compliment if it comes with a request.",
    "Jesus, Superman, and Mother Teresa never made art. Only imperfect beings can make art because art begins in what is broken.",
    "If someone is trying to convince you it’s not a pyramid scheme, it’s a pyramid scheme.",
    "Learn how to tie a bowline knot. Practice in the dark. With one hand. For the rest of your life you’ll use this knot more times than you would ever believe.",
    "If something fails where you thought it would fail, that is not a failure.",
    "Be governed not by the tyranny of the urgent but by the elevation of the important.",
    "Leave a gate behind you the way you first found it.",
    "The greatest rewards come from working on something that nobody has a name for. If you possibly can, work where there are no words for what you do.",
    "A balcony or porch needs to be at least 6 feet (2m) deep or it won’t be used.",
    "Don’t create things to make money; make money so you can create things. The reward for good work is more work.",
    "In all things — except love — start with the exit strategy. Prepare for the ending. Almost anything is easier to get into than out of.",
    "Train employees well enough they could get another job, but treat them well enough so they never want to.",
    "Don’t aim to have others like you; aim to have them respect you.",
    "The foundation of maturity: Just because it’s not your fault doesn’t mean it’s not your responsibility.",
    "A multitude of bad ideas is necessary for one good idea.",
    "Being wise means having more questions than answers.",
    "Compliment people behind their back. It’ll come back to you.",
    "Most overnight successes — in fact any significant successes — take at least 5 years. Budget your life accordingly.",
    "You are only as young as the last time you changed your mind.",
    "Assume anyone asking for your account information for any reason is guilty of scamming you, unless proven innocent. The way to prove innocence is to call them back, or login to your account using numbers or a website that you provide, not them. Don’t release any identifying information while they are contacting you via phone, message or email. You must control the channel.",
    "Sustained outrage makes you stupid.",
    "Be strict with yourself and forgiving of others. The reverse is hell for everyone.",
    "Your best response to an insult is “You’re probably right.” Often they are.",
    "The worst evils in history have always been committed by those who truly believed they were combating evil. Beware of combating evil.",
    "If you can avoid seeking approval of others, your power is limitless.",
    "When a child asks an endless string of “why?” questions, the smartest reply is, “I don’t know, what do you think?”",
    "To be wealthy, accumulate all those things that money can’t buy.",
    "Be the change you wish to see.",
    "When brainstorming, improvising, jamming with others, you’ll go much further and deeper if you build upon each contribution with a playful “yes — and” example instead of a deflating “no — but” reply.",
    "Work to become, not to acquire.",
    "Don’t loan money to a friend unless you are ready to make it a gift.",
    "On the way to a grand goal, celebrate the smallest victories as if each one were the final goal. No matter where it ends you are victorious.",
    "Calm is contagious.",
    "Even a foolish person can still be right about most things. Most conventional wisdom is true.",
    "Always cut away from yourself.",
    "Show me your calendar and I will tell you your priorities. Tell me who your friends are, and I’ll tell you where you’re going.",
    "When hitchhiking, look like the person you want to pick you up.",
    "Contemplating the weaknesses of others is easy; contemplating the weaknesses in yourself is hard, but it pays a much higher reward.",
    "Worth repeating: measure twice, cut once.",
    "Your passion in life should fit you exactly; but your purpose in life should exceed you. Work for something much larger than yourself.",
    "If you can’t tell what you desperately need, it’s probably sleep.",
    "When playing Monopoly, spend all you have to buy, barter, or trade for the Orange properties. Don’t bother with Utilities.",
    "If you borrow something, try to return it in better shape than you received it. Clean it, sharpen it, fill it up.",
    "Even in the tropics it gets colder at night than you think. Pack warmly.",
    "To quiet a crowd or a drunk, just whisper.",
    "Writing down one thing you are grateful for each day is the cheapest possible therapy ever.",
    "When someone tells you something is wrong, they’re usually right. When someone tells you how to fix it, they’re usually wrong.",
    "If you think you saw a mouse, you did. And, if there is one, there are more.",
    "Money is overrated. Truly new things rarely need an abundance of money. If that was so, billionaires would have a monopoly on inventing new things, and they don’t. Instead almost all breakthroughs are made by those who lack money, because they are forced to rely on their passion, persistence and ingenuity to figure out new ways. Being poor is an advantage in innovation.",
    "Ignore what others may be thinking of you, because they aren’t.",
    "Avoid hitting the snooze button. That’s just training you to oversleep.",
    "Always say less than necessary.",
    "You are given the gift of life in order to discover what your gift *in* life is. You will complete your mission when you figure out what your mission is. This is not a paradox. This is the way.",
    "Don’t treat people as bad as they are. Treat them as good as you are.",
    "It is much easier to change how you think by changing your behavior, than it is to change your behavior by changing how you think. Act out the change you seek.",
    "You can eat any dessert you want if you take only 3 bites.",
    "Each time you reach out to people, bring them a blessing; then they’ll be happy to see you when you bring them a problem.",
    "Bad things can happen fast, but almost all good things happen slowly.",
    "Don’t worry how or where you begin. As long as you keep moving, your success will be far from where you start.",
    "When you confront a stuck bolt or screw: righty tighty, lefty loosey.",
    "If you meet a jerk, overlook them. If you meet jerks everywhere everyday, look deeper into yourself.",
    "Dance with your hips.",
    "We are not bodies that temporarily have souls. We are souls that temporarily have bodies.",
    "You can reduce the annoyance of someone’s stupid belief by increasing your understanding of why they believe it.",
    "If your goal does not have a schedule, it is a dream.",
    "All the greatest gains in life — in wealth, relationships, or knowledge —come from the magic of compounding interest — amplifying small steady gains. All you need for abundance is to keep adding 1% more than you subtract on a regular basis.",
    "The greatest breakthroughs are missed because they look like hard work.",
    "People can’t remember more than 3 points from a speech.",
    "I have never met a person I admired who did not read more books than I did.",
    "The greatest teacher is called “doing”.",
    "Finite games are played to win or lose. Infinite games are played to keep the game going. Seek out infinite games because they yield infinite rewards.",
    "Everything is hard before it is easy. The day before something is a breakthrough, it’s a stupid idea.",
    "A problem that can be solved with money is not really a problem.",
    "When you are stuck, sleep on it. Let your subconscious work for you.",
    "Your work will be endless, but your time is finite. You cannot limit the work so you must limit your time. Hours are the only thing you can manage.",
    "To succeed, get other people to pay you; to become wealthy, help other people to succeed.",
    "Children totally accept — and crave — family rules. “In our family we have a rule for X” is the only excuse a parent needs for setting a family policy. In fact, “I have a rule for X” is the only excuse you need for your own personal policies.",
    "All guns are loaded.",
    "Many backward steps are made by standing still.",
    "This is the best time ever to make something. None of the greatest, coolest creations 20 years from now have been invented yet. You are not late.",
    "No rain, no rainbow.",
    "Every person you meet knows an amazing lot about something you know virtually nothing about. Your job is to discover what it is, and it won’t be obvious.",
    "You don’t marry a person, you marry a family.",
    "Always give credit, take blame.",
    "Be frugal in all things, except in your passions splurge.",
    "When making something, always get a few extras — extra material, extra parts, extra space, extra finishes. The extras serve as backups for mistakes, reduce stress, and fill your inventory for the future. They are the cheapest insurance.",
    "Something does not need to be perfect to be wonderful. Especially weddings.",
    "Don’t let your email inbox become your to-do list.",
    "The best way to untangle a knotty tangle is not to “untie” the knots, but to keep pulling the loops apart wider and wider. Just make the mess as big, loose and open as possible. As you open up the knots they will unravel themselves. Works on cords, strings, hoses, yarns, or electronic cables.",
    "Be a good ancestor. Do something a future generation will thank you for. A simple thing is to plant a tree.",
    "To combat an adversary, become their friend.",
    "Take one simple thing — almost anything — but take it extremely seriously, as if it was the only thing in the world, or maybe the entire world is in it — and by taking it seriously you’ll light up the sky.",
    "History teaches us that in 100 years from now some of the assumptions you believed will turn out to be wrong. A good question to ask yourself today is “What might I be wrong about?”",
    "Be nice to your children because they are going to choose your nursing home.",
    "Advice like these are not laws. They are like hats. If one doesn’t fit, try another.",
    "Learn how to learn from those you disagree with, or even offend you. See if you can find the truth in what they believe.",
    "Being enthusiastic is worth 25 IQ points.",
    "Always demand a deadline. A deadline weeds out the extraneous and the ordinary. It prevents you from trying to make it perfect, so you have to make it different. Different is better.",
    "Don’t be afraid to ask a question that may sound stupid because 99% of the time everyone else is thinking of the same question and is too embarrassed to ask it.",
    "Being able to listen well is a superpower. While listening to someone you love keep asking them “Is there more?”, until there is no more.",
    "A worthy goal for a year is to learn enough about a subject so that you can’t believe how ignorant you were a year earlier.",
    "Gratitude will unlock all other virtues and is something you can get better at.",
    "Treating a person to a meal never fails, and is so easy to do. It’s powerful with old friends and a great way to make new friends.",
    "Don’t trust all-purpose glue.",
    "Reading to your children regularly will bond you together and kickstart their imaginations.",
    "Never use a credit card for credit. The only kind of credit, or debt, that is acceptable is debt to acquire something whose exchange value is extremely likely to increase, like in a home. The exchange value of most things diminishes or vanishes the moment you purchase them. Don’t be in debt to losers.",
    "Pros are just amateurs who know how to gracefully recover from their mistakes.",
    "Extraordinary claims should require extraordinary evidence to be believed.",
    "Don’t be the smartest person in the room. Hangout with, and learn from, people smarter than yourself. Even better, find smart people who will disagree with you.",
    "Rule of 3 in conversation. To get to the real reason, ask a person to go deeper than what they just said. Then again, and once more. The third time’s answer is close to the truth.",
    "Don’t be the best. Be the only.",
    "Everyone is shy. Other people are waiting for you to introduce yourself to them, they are waiting for you to send them an email, they are waiting for you to ask them on a date. Go ahead.",
    "Don’t take it personally when someone turns you down. Assume they are like you: busy, occupied, distracted. Try again later. It’s amazing how often a second try works.",
    "The purpose of a habit is to remove that action from self-negotiation. You no longer expend energy deciding whether to do it. You just do it. Good habits can range from telling the truth, to flossing.",
    "Promptness is a sign of respect.",
    "When you are young spend at least 6 months to one year living as poor as you can, owning as little as you possibly can, eating beans and rice in a tiny room or tent, to experience what your “worst” lifestyle might be. That way any time you have to risk something in the future you won’t be afraid of the worst case scenario.",
    "Trust me: There is no “them”.",
    "The more you are interested in others, the more interesting they find you. To be interesting, be interested.",
    "Optimize your generosity. No one on their deathbed has ever regretted giving too much away.",
    "To make something good, just do it. To make something great, just re-do it, re-do it, re-do it. The secret to making fine things is in remaking them.",
    "The Golden Rule will never fail you. It is the foundation of all other virtues.",
    "If you are looking for something in your house, and you finally find it, when you’re done with it, don’t put it back where you found it. Put it back where you first looked for it.",
    "Saving money and investing money are both good habits. Small amounts of money invested regularly for many decades without deliberation is one path to wealth.",
    "To make mistakes is human. To own your mistakes is divine. Nothing elevates a person higher than quickly admitting and taking personal responsibility for the mistakes you make and then fixing them fairly. If you mess up, fess up. It’s astounding how powerful this ownership is.",
    "Never get involved in a land war in Asia.",
    "You can obsess about serving your customers/audience/clients, or you can obsess about beating the competition. Both work, but of the two, obsessing about your customers will take you further.",
    "Show up. Keep showing up. Somebody successful said: 99% of success is just showing up.",
    "Separate the processes of creation from improving. You can’t write and edit, or sculpt and polish, or make and analyze at the same time. If you do, the editor stops the creator. While you invent, don’t select. While you sketch, don’t inspect. While you write the first draft, don’t reflect. At the start, the creator mind must be unleashed from judgement.",
    "If you are not falling down occasionally, you are just coasting.",
    "Perhaps the most counter-intuitive truth of the universe is that the more you give to others, the more you’ll get. Understanding this is the beginning of wisdom.",
    "Friends are better than money. Almost anything money can do, friends can do better. In so many ways a friend with a boat is better than owning a boat.",
    "This is true: It’s hard to cheat an honest man.",
    "When an object is lost, 95% of the time it is hiding within arm’s reach of where it was last seen. Search in all possible locations in that radius and you’ll find it.",
    "You are what you do. Not what you say, not what you believe, not how you vote, but what you spend your time on.",
    "If you lose or forget to bring a cable, adapter or charger, check with your hotel. Most hotels now have a drawer full of cables, adapters and chargers others have left behind, and probably have the one you are missing. You can often claim it after borrowing it.",
    "Hatred is a curse that does not affect the hated. It only poisons the hater. Release a grudge as if it was a poison.",
    "There is no limit on better. Talent is distributed unfairly, but there is no limit on how much we can improve what we start with.",
    "Be prepared: When you are 90% done any large project (a house, a film, an event, an app) the rest of the myriad details will take a second 90% to complete.",
    "When you die you take absolutely nothing with you except your reputation.",
    "Before you are old, attend as many funerals as you can bear, and listen. Nobody talks about the departed’s achievements. The only thing people will remember is what kind of person you were while you were achieving.",
    "For every dollar you spend purchasing something substantial, expect to pay a dollar in repairs, maintenance, or disposal by the end of its life.",
    "Anything real begins with the fiction of what could be. Imagination is therefore the most potent force in the universe, and a skill you can get better at. It’s the one skill in life that benefits from ignoring what everyone else knows.",
    "When crisis and disaster strike, don’t waste them. No problems, no progress.",
    "On vacation go to the most remote place on your itinerary first, bypassing the cities. You’ll maximize the shock of otherness in the remote, and then later you’ll welcome the familiar comforts of a city on the way back.",
    "When you get an invitation to do something in the future, ask yourself: would you accept this if it was scheduled for tomorrow? Not too many promises will pass that immediacy filter.",
    "Don’t say anything about someone in email you would not be comfortable saying to them directly, because eventually they will read it.",
    "If you desperately need a job, you are just another problem for a boss; if you can solve many of the problems the boss has right now, you are hired. To be hired, think like your boss.",
    "Art is in what you leave out.",
    "Acquiring things will rarely bring you deep satisfaction. But acquiring experiences will.",
    "Rule of 7 in research. You can find out anything if you are willing to go seven levels. If the first source you ask doesn’t know, ask them who you should ask next, and so on down the line. If you are willing to go to the 7th source, you’ll almost always get your answer.",
    "How to apologize: Quickly, specifically, sincerely.",
    "Don’t ever respond to a solicitation or a proposal on the phone. The urgency is a disguise.",
    "When someone is nasty, rude, hateful, or mean with you, pretend they have a disease. That makes it easier to have empathy toward them which can soften the conflict.",
    "Eliminating clutter makes room for your true treasures.",
    "You really don’t want to be famous. Read the biography of any famous person.",
    "Experience is overrated. When hiring, hire for aptitude, train for skills. Most really amazing or great things are done by people doing them for the first time.",
    "A vacation + a disaster = an adventure.",
    "Buying tools: Start by buying the absolute cheapest tools you can find. Upgrade the ones you use a lot. If you wind up using some tool for a job, buy the very best you can afford.",
    "Learn how to take a 20-minute power nap without embarrassment.",
    "Following your bliss is a recipe for paralysis if you don’t know what you are passionate about. A better motto for most youth is “master something, anything”. Through mastery of one thing, you can drift towards extensions of that mastery that bring you more joy, and eventually discover where your bliss is.",
    "I’m positive that in 100 years much of what I take to be true today will be proved to be wrong, maybe even embarrassingly wrong, and I try really hard to identify what it is that I am wrong about today.",
    "Over the long term, the future is decided by optimists. To be an optimist you don’t have to ignore all the many problems we create; you just have to imagine improving our capacity to solve problems.",
    "The universe is conspiring behind your back to make you a success. This will be much easier to do if you embrace this pronoia."
]